# Generated by Django 3.2.25 on 2024-12-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('number_of_lectures', models.IntegerField()),
                ('est_time', models.IntegerField()),
                ('short_description', models.TextField(max_length=255)),
                ('long_description', models.TextField(max_length=1000)),
                ('test', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(max_length=255)),
                ('full_content', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
