# Generated by Django 3.2.25 on 2024-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='starting_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
