# Generated by Django 4.2.17 on 2025-01-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241207_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='short_description',
            new_name='material_title',
        ),
    ]
